version: '3.8'

services:
  code-dock-app:
    image: ${DOCKER_IMAGE:-himerman/code-dock:latest} # Default image if not set in .env
    container_name: code-dock
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - "${API_PORT_HOST:-30089}:${API_PORT_CONTAINER:-30089}"
      - "${WEB_PORT_HOST:-30090}:${WEB_PORT_CONTAINER:-30090}"
    volumes:
      # Host Path : Container Path
      - ./codebases:/app/codebases
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    # Load environment variables from .env file in the same directory
    env_file:
      - ./.env

volumes:
  codebases:
  uploads:
  logs: 